apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    type: production

spec:
  containers:
  - name: my-nginx
    image: nginx
  - name: my-busybox
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    
    