apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser_deploy
  namespace: blue

subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: role-deploy
  apiGroup: rbac.authorization.k8s.io