apiVersion: app/v1
kind: ReplicaSet
metadata: 
    name: my-replication
    labels:
        app: my-app
        type: front-end

spec:
    template:
        metadata:
          name: myapp-pod
          labels:
            app: my-app
            type: front-end

        spec:
          containers:
          - name: my-nginx
            image: nginx

    replicas: 2
    selector: 
      matchLabels: 
        type: front-end



    
        