apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-replica
    labels: 
      type: front-end 

spec:
    selector:
        matchLabels:
            type: production

    replicas: 3

    template:
      metadata:
        name: mynginx-pod
        labels:
          type: production

      spec:
        containers:
        - name: my-nginx
          image: nginx 