# kubectl get pods elephant -o yaml > pod.yml
apiVersion: v1
kind: Pod
metadata: 
  name: elephant
  labels: 
    app: my-pod

spec: 
  containers: 
  - name: elephant
    image: polinux/stress  
    resources: 
      requests:
        memory: "10Mi"
        cpu: 1
      limits: 
        memory: "20Mi"
        cpu: 2
