# kubectl run --restart=Never --image=busybox static-busybox --dry-run=client -o yaml --command -- sleep 1000 > 
# /etc/kubernetes/manifests/static-busybox.yaml
apiVersion: v1
kind: Pod
metadata: 
  name: static-busybox

spec: 
  containers:
  - name: static-busybox
    image: busybox