# kubectl create -f voting-app-pod.yml
# kubectl create -f voting-app-service.yml

# kubectl create -f result-app-pod.yml
# kubectl create -f result-app-service.yml

# kubectl create -f redis-pod.yml
# kubectl create -f redis-service.yml

# kubectl create -f postgres-pod.yml
# kubectl create -f postgres-service.yml

# kubectl create -f worker-app-pod.yml

##### In one Command
## Start

# kubectl create -f voting-app-pod.yml; kubectl create -f voting-app-service.yml; kubectl create -f result-app-pod.yml; kubectl create -f result-app-service.yml; kubectl create -f redis-pod.yml; kubectl create -f redis-service.yml; kubectl create -f postgres-pod.yml; kubectl create -f postgres-service.yml; kubectl create -f worker-app-pod.yml

## Ends

## Start Deployment

# create -f voting-app-deploy.yml
# kubectl create -f voting-app-service.yml

# kubectl create -f redis-app-deploy.yml
# kubectl create -f redis-service.yml

# kubectl create -f postgres-app-deploy.yml
# kubectl create -f postgres-service.yml

# kubectl create -f result-app-deploy.yml
# kubectl create -f result-app-service.yml

# kubectl create -f worker-app-deploy.yml