apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-app-service
    type: demo-voting-app

spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app