apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blue

spec: 
  replicas: 6

  selector: 
    matchLabels:
      tier: frontend

  template: 
    metadata: 
      name: my-pod
      labels: 
        tier: frontend

    spec:
      containers: 
      - name: blue
        image: nginx

      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values: 
                - blue