apiVersion: apps/v1
kind: Deployment
metadata: 
  name: red
  labels: 
    app: my-deploy

spec: 
  replicas: 3
  selector: 
    matchLabels: 
      type: binding

  template: 
    metadata: 
      name: red
      labels: 
        type: binding

    spec: 
      containers: 
      - name: red
        image: nginx
      
      affinity: 
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms: 
            - matchExpressions: 
              - key: node-role.kubernetes.io/master
                operator: Exists
