apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    tier: frontend

spec:
  containers: 
  - name: blue
    image: nginx

  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          matchExpression:
          - key: color
            operator: In
            values: 
            - blue
