apiVersion: v1
kind: Pod
metadata:
  name: webapp

spec: 
  containers: 
  - name: webapp
    image: kodekloud/event-simulator
    volumeMounts: 
    - mountPath: /log
      name: my-vol

  volumes: 
  - name: my-vol
    hostPath: 
      path: /var/log/webapp
      type: Directory