apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: elasticsearch
  namespace: kube-system
  labels: 
    tier: frontend

spec:
   selector: 
     matchLabels: 
       app: my-app

   template:
     metadata: 
       name: my-pod
       labels: 
         app: my-app
     spec: 
       containers: 
       - name: elasticsearch
         image: k8s.gcr.io/fluentd-elasticsearch:1.20