apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deploy
    labels: 
      type: front-end 

spec:
    selector:
        matchLabels:
            type: production

    replicas: 6

    template:
      metadata:
        name: mynginx-pod
        labels:
          type: production
          tier: front-end

      spec:
        containers:
        - name: my-nginx
          image: nginx 