apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysqll
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        resources: {}
status: {}


apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: mysqll
spec:
  type: NodePort
  ports:
  - targetPort: 3306
    ports: 3306
    nodePort: 32000