name: Deploy IBM MQ Connector

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy IBM MQ Connector
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./IBM-MQ-Connector

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Compose
        run: |
          docker compose build --no-cache

      - name: Start Docker Compose services
        run: |
          docker compose up -d

      - name: Check deployment
        run: |
          docker compose ps -a

      - name: Sleep for 10 min
        run: |
          echo "Waiting for services to initialize..."
          sleep 600
      
      - name: Check Worker Status
        run: |
          echo "Checking Kafka Connect worker status..."
          curl -X GET http://localhost:8083/

      # - name: Delete Connector
      #   run: |
      #     curl -X DELETE http://localhost:8083/connectors/ibm-mq-source-connector

      # - name: Sleep for 2 min
      #   run: |
      #     echo "Waiting for services to initialize..."
      #     sleep 120
      
      - name: Check Connector List
        run: |
          echo "Checking existing connectors..."
          curl http://0.0.0.0:8083/connectors/
      
      - name: Verify IBM MQ Connector Registration
        run: |
          echo "Verifying IBM MQ Connector registration..."
          curl -X GET http://localhost:8083/connectors/ibm-mq-source-connector/config || echo "Connector not registered!"

      - name: Add Messages to IBM MQ
        run: |
          docker exec -i ibm-mq-connector-ibm-mq-1 bash -c "echo '{\"payload\": \"Hello from IBM MQ Git Workflow\"}' | /opt/mqm/samp/bin/amqsput DEV.QUEUE.1 QM1"
      
      # - name: POST IBM config to connector
      #   run: |
      #     for i in {1..5}; do
      #       curl -X POST -H "Content-Type: application/json" --data @config/ibm-mq-source.json http://localhost:8083/connectors && break || sleep 10
      #     done
      
      - name: Check Connector List & Status
        run: |
          curl http://0.0.0.0:8083/connectors/
          curl http://0.0.0.0:8083/connectors?expand=info&expand=status

      - name: Sleep for 3 min
        run: sleep 180
